version: '3.8'

services:
  mysql:
    container_name: mysql_financial_control
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_DATABASE: mydatabase
      DB_USER: user
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
      KC_HOSTNAME: localhost
      KC_PROXY: edge
      # Use as opções abaixo para configurar o Keycloak em modo autônomo
      KC_DB_URL_HOST: mysql
      KC_DB_URL_PORT: 3306
      KC_DB_URL_DATABASE: mydatabase
    ports:
      - "8181:8181"
    depends_on:
      - mysql
    command: start-dev

volumes:
  mysql_data:
